// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lsp.proto

package gauge_messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Empty is a blank response, to be used when there is no return expected.
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func init() {
	proto.RegisterType((*Empty)(nil), "gauge.messages.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LspService service

type LspServiceClient interface {
	GetStepNames(ctx context.Context, in *StepNameRequest, opts ...grpc.CallOption) (*StepNameResponse, error)
	CacheFile(ctx context.Context, in *CacheFileRequest, opts ...grpc.CallOption) (*Empty, error)
	GetStepPositions(ctx context.Context, in *StepPositionsRequest, opts ...grpc.CallOption) (*StepPositionsResponse, error)
	GetImplementationFiles(ctx context.Context, in *ImplementationFileListRequest, opts ...grpc.CallOption) (*ImplementationFileListResponse, error)
	ImplementStub(ctx context.Context, in *StubImplementationCodeRequest, opts ...grpc.CallOption) (*FileDiff, error)
}

type lspServiceClient struct {
	cc *grpc.ClientConn
}

func NewLspServiceClient(cc *grpc.ClientConn) LspServiceClient {
	return &lspServiceClient{cc}
}

func (c *lspServiceClient) GetStepNames(ctx context.Context, in *StepNameRequest, opts ...grpc.CallOption) (*StepNameResponse, error) {
	out := new(StepNameResponse)
	err := grpc.Invoke(ctx, "/gauge.messages.lspService/GetStepNames", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lspServiceClient) CacheFile(ctx context.Context, in *CacheFileRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/gauge.messages.lspService/CacheFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lspServiceClient) GetStepPositions(ctx context.Context, in *StepPositionsRequest, opts ...grpc.CallOption) (*StepPositionsResponse, error) {
	out := new(StepPositionsResponse)
	err := grpc.Invoke(ctx, "/gauge.messages.lspService/GetStepPositions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lspServiceClient) GetImplementationFiles(ctx context.Context, in *ImplementationFileListRequest, opts ...grpc.CallOption) (*ImplementationFileListResponse, error) {
	out := new(ImplementationFileListResponse)
	err := grpc.Invoke(ctx, "/gauge.messages.lspService/GetImplementationFiles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lspServiceClient) ImplementStub(ctx context.Context, in *StubImplementationCodeRequest, opts ...grpc.CallOption) (*FileDiff, error) {
	out := new(FileDiff)
	err := grpc.Invoke(ctx, "/gauge.messages.lspService/ImplementStub", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LspService service

type LspServiceServer interface {
	GetStepNames(context.Context, *StepNameRequest) (*StepNameResponse, error)
	CacheFile(context.Context, *CacheFileRequest) (*Empty, error)
	GetStepPositions(context.Context, *StepPositionsRequest) (*StepPositionsResponse, error)
	GetImplementationFiles(context.Context, *ImplementationFileListRequest) (*ImplementationFileListResponse, error)
	ImplementStub(context.Context, *StubImplementationCodeRequest) (*FileDiff, error)
}

func RegisterLspServiceServer(s *grpc.Server, srv LspServiceServer) {
	s.RegisterService(&_LspService_serviceDesc, srv)
}

func _LspService_GetStepNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspServiceServer).GetStepNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gauge.messages.lspService/GetStepNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspServiceServer).GetStepNames(ctx, req.(*StepNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LspService_CacheFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspServiceServer).CacheFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gauge.messages.lspService/CacheFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspServiceServer).CacheFile(ctx, req.(*CacheFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LspService_GetStepPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspServiceServer).GetStepPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gauge.messages.lspService/GetStepPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspServiceServer).GetStepPositions(ctx, req.(*StepPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LspService_GetImplementationFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImplementationFileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspServiceServer).GetImplementationFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gauge.messages.lspService/GetImplementationFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspServiceServer).GetImplementationFiles(ctx, req.(*ImplementationFileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LspService_ImplementStub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubImplementationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspServiceServer).ImplementStub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gauge.messages.lspService/ImplementStub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspServiceServer).ImplementStub(ctx, req.(*StubImplementationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LspService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gauge.messages.lspService",
	HandlerType: (*LspServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStepNames",
			Handler:    _LspService_GetStepNames_Handler,
		},
		{
			MethodName: "CacheFile",
			Handler:    _LspService_CacheFile_Handler,
		},
		{
			MethodName: "GetStepPositions",
			Handler:    _LspService_GetStepPositions_Handler,
		},
		{
			MethodName: "GetImplementationFiles",
			Handler:    _LspService_GetImplementationFiles_Handler,
		},
		{
			MethodName: "ImplementStub",
			Handler:    _LspService_ImplementStub_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lsp.proto",
}

func init() { proto.RegisterFile("lsp.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x41, 0x51, 0xd9, 0x41, 0x8b, 0x0e, 0x28, 0xb2, 0x17, 0x45, 0xf4, 0x68, 0x0e, 0xfa,
	0x06, 0xee, 0x6a, 0x11, 0x54, 0xd4, 0x5e, 0xbc, 0x49, 0x76, 0x9d, 0xad, 0x81, 0xa6, 0x89, 0x3b,
	0x53, 0xc5, 0x57, 0xf2, 0x8d, 0x7c, 0x1b, 0x69, 0x6d, 0x02, 0xdb, 0x2a, 0x7a, 0x0b, 0xf9, 0x3e,
	0xfe, 0xff, 0x27, 0x81, 0x41, 0xc1, 0x5e, 0xf9, 0xb9, 0x13, 0x87, 0x49, 0xae, 0xab, 0x9c, 0x94,
	0x25, 0x66, 0x9d, 0x13, 0x0f, 0x93, 0x70, 0xfa, 0xe6, 0x07, 0x6b, 0xb0, 0x72, 0x6e, 0xbd, 0xbc,
	0x9f, 0x7c, 0x2e, 0x03, 0x14, 0xec, 0x33, 0x9a, 0xbf, 0x9a, 0x29, 0xe1, 0x1d, 0xac, 0xa7, 0x24,
	0x99, 0x90, 0xbf, 0xd1, 0x96, 0x18, 0xf7, 0xd4, 0x62, 0x90, 0x0a, 0xe8, 0x9e, 0x5e, 0x2a, 0x62,
	0x19, 0xee, 0xff, 0x2e, 0xb0, 0x77, 0x25, 0x13, 0x8e, 0x61, 0x30, 0xd2, 0xd3, 0x67, 0xba, 0x30,
	0x05, 0x61, 0x4f, 0x8f, 0x28, 0x04, 0x6e, 0x77, 0x8d, 0x66, 0x27, 0x3e, 0xc2, 0x66, 0x3b, 0xec,
	0xd6, 0xb1, 0x11, 0xe3, 0x4a, 0xc6, 0xc3, 0x9f, 0xba, 0x23, 0x0e, 0x81, 0x47, 0x7f, 0x58, 0xed,
	0xcc, 0x37, 0xd8, 0x49, 0x49, 0x2e, 0xad, 0x2f, 0xc8, 0x52, 0x29, 0xba, 0xa6, 0xf5, 0x2e, 0xc6,
	0xe3, 0x6e, 0x40, 0x5f, 0xba, 0x32, 0x2c, 0xa1, 0x4f, 0xfd, 0x57, 0x6f, 0x8b, 0x1f, 0x60, 0x23,
	0x1a, 0x99, 0x54, 0x93, 0x7e, 0x5f, 0x7d, 0xbb, 0x18, 0x32, 0x72, 0x4f, 0xf1, 0xc1, 0x76, 0xbb,
	0x7a, 0xdd, 0x30, 0x36, 0xb3, 0xd9, 0xd9, 0xd6, 0xc7, 0x52, 0x92, 0x36, 0xec, 0xba, 0x65, 0x93,
	0xd5, 0xe6, 0xfb, 0x4f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x94, 0x20, 0xac, 0xc0, 0x2b, 0x02,
	0x00, 0x00,
}
